### ISSUE TITLE
Why use Client Server while designing P2P program?

### ISSUE THREAD

**Issue by kitescat** [Shadat-tonmoy/P2P-Chatting-And-File-Sharing-App#1]
hello,can i ask why use Client Server while designing P2P program?i cant understand how to design P2P program for LAN Communication System.i  woulc be grateful if u answer my question as soon as possible

**Comment by Shadat-tonmoy** [comment]
Hi there, Thanks for your query...Here by using the terminology client-server I just wanted to indicate one computer will work as client and another as server. P2P (Peer to peer) is used to transfer data from one computer to another....In the client server model the server is indeed a computer. And a client (Which is also a computer) gets data from server PC. Using client-server It is just a terminological dogma...nothing else....I hope i am able to make it clear to you!

**Comment by kitescat** [comment]
thx for your answer，I seem to understand what you mean.The P2P program can be used as both server and server, so do you write the same thing?(which  i've learned from our textbook).i mean server  can also be client client can also be server.

**Comment by Shadat-tonmoy** [comment]
Yes....Just think of two pc A and B when A is receiving data from B then A is client and B is server....but when B is receiving data from A situation swapped...then B is client A is server...that is server can be client and client can be server as you mentioned 😁

**Comment by kitescat** [comment]
thx bro, i also want to ask how u make it possible to transport files(sharing or transporting )? are they the same meaning in your app.i must have read your program as quick  as possible so plz tell me sth .
thank u vey much!

**Comment by Shadat-tonmoy** [comment]
Yes this is tje same meaning...I just converted the file contents into bytes or may be bytestream from the sender end and receive the bytes at reciver end...then convert the byte back into a file in the reciever end...
